language: go
go:
  - 1.11.x
  - 1.12.x
  - 1.13.x
  - master
env:
  global:
    - GO111MODULE=on
before_install:
  - go get github.com/golangci/golangci-lint/cmd/golangci-lint
  - go get github.com/mattn/goveralls
  - export PATH="$GOPATH/bin:$PATH"
script:
  - golangci-lint run
  - goveralls --service=travis-ci -package .
